### ISSUE TITLE
[Release] v1.0.0

### ISSUE THREAD

**Issue by unnnyong** [Async-Swift/AsyncSwift#21]
## TODO

- [x] App Store screen shots
- [x] App Store description
- [x] v1.0 Release note
- [ ] [QA](https://docs.google.com/spreadsheets/d/1UwJ8Hw2h-ybMH9nV65jGiMLj1ITbm950QAZbOcGZXZM/edit#gid=0) 작성중

## Release note

-
